### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by herodrigues** [dog-days/antd-form-component#4]
@xianshannan I saw this project is a refactor of another project of yours. I'd like to know if this current project is still necessary based on the two reasons you give on the README file.

I'm asking this because I want to continue improving this project, but I'm not sure if Ant Design of React has implemented those missing features yet.

Thanks in advance.

**Comment by samonxian** [comment]
Ant Design of React t has not supported these features yet, and will not implement these features.
The purpose of this project is to simplify the use of form components and to handle the problem of repeated renderings. The problem of repeated rendering is actually acceptable if the form components is not a lot.

**Comment by herodrigues** [comment]
Thanks for asnwering, @xianshannan!
All clear now.
